hepsi:derle calistir
derle:
	g++ -I ./include/ -o ./lib/ogrenci -c ./src/ogrenci.cpp
	g++ -I ./include/ -o ./lib/sinif -c ./src/sinif.cpp
	g++ -I ./include/ -o ./lib/okul -c ./src/okul.cpp
	g++ -I ./include/ -o ./lib/yonetim -c ./src/yonetim.cpp
	g++ -I ./include/ -o ./lib/test -c ./src/test.cpp
	g++ ./lib/ogrenci ./lib/sinif ./lib/okul ./lib/yonetim ./lib/test -o ./bin/test 
calistir:
	./bin/test

