#Cengiz Altürk 	G140910048
#Çağdaş Bilgin	G141210045
#Elmar Dadaşov 	G151210564
#Merve Dolapcı 	G141210048
#Neslihan Yakay G151210018


hepsi:derle calistir
derle:
	g++ -I ./include/ -o ./lib/shell -c ./src/shell.c
	g++ -I ./include/ -o ./bin/main ./lib/shell ./src/main.c
calistir:
		./bin/main
